# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"

  # Add forwarded ports
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 4444, host: 4444
  config.vm.network "forwarded_port", guest: 5900, host: 5900
  

  config.vm.synced_folder ".", "/vagrant", disabled: false
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # Setup Test env
  config.vm.provision "shell", privileged: false, inline: "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
  config.vm.provision "shell", privileged: false, inline: "curl -sSL https://get.rvm.io | bash -s stable"
  config.vm.provision "shell", privileged: false, inline: "source '/home/vagrant/.rvm/bin/rvm-exec' && yes | rvm install 2.4"
  
  
  config.vm.provision :docker

  # Install the plugin: vagrant plugin install vagrant-docker-compose
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", rebuild: true, run: "always"
   
end